dhbw-ma-ppp/ppp-2023

Exercises/Utku Acikel/exercises_02.py

Week 2 Utku Acikel

---

Exercises/LauravanUffelt/VL2 Lösungen.py

Lösungen Woche 2

---

Exercises/Corvin Ansorge/exercises_03.py

Final Exercise_03

---

Exercises/BoWichtendahl/exercises_03.py

Bo Wichtendahl Week 03 (result task 3: 1306)

---

Exercises/PaulSeidel/PSeidel_exercises_04.py

PSeidel_exercise04

---

Exercises/LauravanUffelt/VL3 Lösungen.py

Lösungen Woche 3

---

Exercises/LauravanUffelt/VL 4 Lösungen.py

Please review:
solution to task: 16694270

Lösungen Woche 4

---

Exercises/Utku Acikel/exercises_04.py

Week 4 Utku Acikel

---

Exercises/GerritFritz/exercises_03.py

Gerrit Fritz Woche 3 1306

---

Exercises/Felix Regnier/ex03_Felix_Regnier.py

Neue pull request, da die Aufgaben der vorherigen Wochen noch hinterlegt waren.
Außerdem habe ich als Ergebnis für Part 3 "1306", was ich nicht in der pull request geschrieben hatte.

Aufgaben 03 Felix Regnier

---

Exercises/Felix Regnier/ex04_Felix_Regnier.py

Die Aufgaben sind leider noch nicht fertig. Ich versuche die Fehler am Wochenende noch zu beheben.

Aufgaben Woche 04 Felix Regnier

---

Exercises/Utku Acikel/exercises_03.py

Please Review
Part 3 Result: 1306

Utku Acikel Week 3

---

Exercises/JanMerz/exercises_03.py

Jan Merz Exercise 03

---

Exercises/FabianSchwarz/exercises_04.py

Merging Solution for week 4 into main. the computer printed out the value 16694270.

Merging solution for Woche 4 

---

Exercises/JonasPutz/exercises_03.py

Solution to excercise 3:
1306
Execution time:
3.693796000443399ms

Jonas Week03

---

Exercises/JonasPutz/exercises_04.py

Jonas-Week04 (16694270)

---

Exercises/JohannesLingk/exercises_03.py

Johannes Lingk Week 3.

---

Exercises/JohannesLingk/exercises_04.py

Johannes Lingk Week 4

---

Exercises/GerritFritz/exercises_05.py

Aufgabe 1:
1639024365
Aufgabe 2:
6260

Gerrit Fritz Aufgabe 5: 1639024365, 6260

---

Exercises/BoWichtendahl/exercises_06.py

The sum of the sizes of all directories with a maximal size of `100000` is: `1778099`
The directory to delete has the following path: `/pcqjnl/lrrl/nwjggvr/bwmglvmt/`
`1623571` Storage Units will be freed, leaving `13997` free after the Update

Bo Wichtendahl 06 (Task 1: 1778099, Task 2: 1623571)

---

Exercises/JasminSteidl/Übung6.py

Ich hab da völlig falsche Werte raus, weiß aber nicht wieso, wenn also jemand sich das anschauen könnte und Veränderungen vorschlagen könnte, wäre ich sehr dankbar.

Aufgabe06 Jasmin 1778099, 1623571

---

Exercises/JanMerz/exercises_06.py

task 1: 1778099
task 2: 1623571

Loesung_06 Jan Merz (1778099, 1623571)

---

Exercises/Tom_Knoden/Woche02_reupload.py

As stated in the title, this PR simply is a reupload of my solution for week 01. There have been problems concerning the former branch in which the file was located in. These problems have been fixed.

Reupload zu Woche 02

---

Exercises/Tom_Knoden/Woche03_reupload.py

As stated in the title, this PR simply is a reupload of my solution for week 01. There have been problems concerning the former branch in which the file was located in. These problems have been fixed.
Also there have been some improvements made to the code that should enhance it's functionality and efficiency.

Reupload zu Woche 03

---

Exercises/Tom_Knoden/Woche04_reupload.py

As stated in the title, this PR simply is a reupload of my solution for week 01. There have been problems concerning the former branch in which the file was located in. These problems have been fixed.
Also there have been some improvements made to the code that should enhance it's functionality and efficiency.

Reupload zu Woche 04 (16694270)

---

Exercises/JonasPutz/exercises_05.py

Task 1:
1639024365 at index 653
Task 2:
6260 bags

Jonas-Week05

---

Exercises/JonasPutz/exercises_06.py

Taks 1:
the total sum of all directories smaller than 100000 is 1778099
Task 2:
To make space for the file with a size of 30000000, something greater than 1609574 has to be deleted:
Found directory: bwmglvmt at \pcqjnl\lrrl\nwjggvr\bwmglvmt with a size of 1623571

Jonas-Week06 (1778099, 1623571)

---

Exercises/JonasPutz/exercises_07.py
Exercises/JonasPutz/exercises_07_breakoutgui.py
Exercises/JonasPutz/exercises_07_computer.py

Board for Task 1:
Total Score for Task 2:
17159

Jonas-Week07(17159)

---

Exercises/JanMerz/exercises_07.py

This task was pair programmed by Jasmin Steidl and Jan Merz.
> While the first part of the task is working fine, the second task is not working how its supposed to and we cant find the Error.
> The way the code is written right now the program works for two frames and is then exited because of opcode 99. 
> In these two frames the ball is moving towards the lower right part of the window and the paddle is moving in the same direction.
> If the input_getter function is returning zero from the start (meaning the paddle is not moving at all) the ball is going up and breaking a block first, instead of going straight down.
> We couldnt find out why this is the case.
Update:
Fixed several bugs in the program, including using the wrong coordinates to calculate the coordinate of the ball. The …

Jasmin_Steidl_Jan_Merz_Exercise_07 (Score: 17159)

---

Exercises/Corvin Ansorge/exercises_05.py

Part 1: 1639024365
Part 2: 6260

Solution Exercise_05

---

Exercises/JasminSteidl/Übung7.py

See Jasmin_Steidl_Jan_Merz_Unfinished_Exercise_07.

Aufgaben 7 Jan und Jasmin

---

Exercises/PaulSeidel/PSeidel_exercises_05.py

Task 1 finished, Task 2 not completely
Task 1 output: "the integer at sequence[653] = 1639024365 can't be build out of the 25 Integers in front of it!"

PaulSeidel_Exercises05 (1639024365/ 6260) finished

---

Exercises/Corvin Ansorge/exercises_06.py

Part 1: 1778099
Part 2: 1623571

Solution Exercise_06

---

Exercises/JohannesLingk/exercises_05.py

Answer 1: 1639024365
Answer 2: 6260

Johannes Lingk Solution Week 5

---

Exercises/Utku Acikel/exercises_05.py

Task 1: 1639024365 / Task 2: 6260

Week 5 Utku Acikel

---

Exercises/Utku Acikel/exercises_08.ipynb

To view file as Jupyter Notebook, go to File changed --> Press the 3 dots at the right top side --> View File
The Table of Contents links somehow wont work on Github

Week 8 Utku Acikel

---

Exercises/RobertWalz/exercises_06/classes.py
Exercises/RobertWalz/exercises_06/main.py

Task 1: 1778099
Task 2: ('/pcqjnl/lrrl/nwjggvr/bwmglvmt'), 1623571)

Robert Walz Woche06

---

Exercises/RobertWalz/exercises_07/computer.py
Exercises/RobertWalz/exercises_07/main.py

I extended my own computer to support the new features and partnered up for task 1 and 2 with @fabischw 
My highscore is 91, because it is very hard to play manually.

Robert Walz Woche07

---

Exercises/PaulSeidel/P.Seidel_exercises_09.ipynb

We did Pairprogramming. So every changes will be committed in the PR of Raphael.

Exercises 09 - Raphael and Paul (0.56)

---

Exercises/Utku Acikel/exercises_09.ipynb

Utku Acikel / Felix Regnier 09 MCC: 0.581674631393

---

Exercises/LauravanUffelt/VL7 Lösungen.py
Exercises/LauravanUffelt/int_computer.py

Laura Lösung Woche 7 (17159)

---

Exercises/JonasPutz/exercises_08.py

Analysis conclusion:
People with one of these attributes have a higher chance of surviving:
Females, 1st class passengers, young children, no relatives onboard.
In total, the only relevant columns for the analysis are:
Sex, Pclass, Age and Fam
Complete analysis
[Titanic Analysis.pdf](https://github.com/dhbw-ma-ppp/ppp-2023/files/13510768/Titanic.Analysis.pdf)

Jonas week08

---

Exercises/JuliusDralle/exercises_09.py

I had 0.53634178089057 at the very first run
I was able to reach a MC of 70% on both validating and training data

Julius Dralle - Exercise 09(0.53634178089057)

---

Exercises/JonasPutz/exercises_09.py

With a decision tree, i couldn't improve over an MCC of 0.6551476590190098 in the training csv, which produzed a MCC of 0.6481979128125026 for the test csv

Solution Week-09: MCC = 0.6481979128125026
